{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tangem.tangem-sdk-kotlin",
    "module": "core",
    "version": "3.9.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-3.9.2.jar",
          "url": "core-3.9.2.jar",
          "size": 2852456,
          "sha512": "938b3cdd06d38108d03804a278c34e32d229203604648bd48692883dcb424c38a2586d2608e8e027f94b6661d363c7c65b837a9329c826cdaf83823390cd1001",
          "sha256": "388fe385a6bb84cd56789733f797ef0ec7fdbba1e277e80ec5ca06e23d7a5732",
          "sha1": "a75b544f0df60d4e7db128f6c1f133fed81e9dfe",
          "md5": "5ce1b9915bff34a5dbd3fa2016c94b54"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.ionspin.kotlin",
          "module": "bignum",
          "version": {
            "requires": "0.3.8"
          }
        },
        {
          "group": "net.i2p.crypto",
          "module": "eddsa",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "org.chiachat",
          "module": "kbls",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.madgag.spongycastle",
          "module": "core",
          "version": {
            "requires": "1.58.0.0"
          }
        },
        {
          "group": "com.madgag.spongycastle",
          "module": "prov",
          "version": {
            "requires": "1.58.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-jvm",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.15.1"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.15.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-3.9.2.jar",
          "url": "core-3.9.2.jar",
          "size": 2852456,
          "sha512": "938b3cdd06d38108d03804a278c34e32d229203604648bd48692883dcb424c38a2586d2608e8e027f94b6661d363c7c65b837a9329c826cdaf83823390cd1001",
          "sha256": "388fe385a6bb84cd56789733f797ef0ec7fdbba1e277e80ec5ca06e23d7a5732",
          "sha1": "a75b544f0df60d4e7db128f6c1f133fed81e9dfe",
          "md5": "5ce1b9915bff34a5dbd3fa2016c94b54"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-3.9.2-sources.jar",
          "url": "core-3.9.2-sources.jar",
          "size": 254594,
          "sha512": "3992c450a4d29b45c6e18a8873014ef7798fc19d5578948e720fe6dcef5d327a442c350161d750b2650111543f680ebe95d9a2ee4fc0604b8419eca451383837",
          "sha256": "742545c6ab624b3d524d4c88463306df80cf83325faa46126a6596bff491dcd8",
          "sha1": "b433698da72ef3552be1249c252dffe55b8deaa4",
          "md5": "8fb5f801eb6f1a076b0610d83c275765"
        }
      ]
    }
  ]
}
